--- #YAML:1.0
name:                StupidMarkov
version:             0.001
abstract:            A stupid Markov chain implementation.
license:             ~
author:              
    - June R. Tate-Gans <june@theonelab.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
